name: Android CI

on:
  pull_request:
    branches: [main,develop]

  workflow_dispatch:


jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@6

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: run unit tests
        run: ./gradlew test